# Generated by Django 4.2.5 on 2023-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="newspaper_images"
            ),
        ),
    ]
