# Generated by Django 4.2.5 on 2023-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0002_alter_newspaper_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="image",
            field=models.ImageField(null=True, upload_to="newspaper_images"),
        ),
    ]
