# Generated by Django 4.2.5 on 2023-09-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0003_alter_newspaper_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="newspaper_images/redactors"),
        ),
    ]
