# Generated by Django 4.2.5 on 2023-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0004_redactor_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="redactors"),
        ),
    ]
